name: example
description: "An example project for the PWA Manager package"
publish_to: 'none'
version: 1.2.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  pwa_manager:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
